#!/bin/bash
choices="New\nShuffle"
choice=$(echo -e $choices | fzf)
case $choice in
  New) fd "\.mp3|\.flac|.\wav" ${MUSIC_DIR} -t file --exec-batch ls -t > ${INT}/Music.m3u;; 
  Shuffle) fd "\.mp3|\.flac|.\wav" ${MUSIC_DIR} -t file | shuf > ${INT}/Music.m3u;;
esac 

